feat: Add PHP `extensions` handling.
WyriHaximus/github-action-composer-php-versions-in-range pull request #12
Opened 2022-08-14 21:53 UTC by drupol

Hi,

Here's a small feature I just added that would be useful for me.

Basically, it infers PHP `extensions` from `composer.json`.

Let me know what you think.

2022-08-18 20:31 UTC, WyriHaximus commented
@drupol Thanks for filing, loving the suggestion. But could you add the list of extensions as output to the CI workflow? https://github.com/WyriHaximus/github-action-composer-php-versions-in-range/blob/main/.github/workflows/ci.yml

2022-08-18 20:36 UTC, drupol commented
> @drupol Thanks for filing, loving the suggestion. But could you add the list of extensions as output to the CI workflow? https://github.com/WyriHaximus/github-action-composer-php-versions-in-range/blob/main/.github/workflows/ci.yml

I'm afraid I have no idea how to do that :(

Feel free to commit in this PR if you want.

2022-08-19 10:09 UTC, WyriHaximus commented
> I'm afraid I have no idea how to do that :(

Want me to guide you through that in this PR?

2022-08-19 10:13 UTC, drupol commented
Of course, all the help is welcome.

2022-08-20 20:32 UTC, WyriHaximus requested changes
The code all looks good, however, there are two things missing. Most importantly an example in the readme on how to use this in a workflow.

Secondly, it's missing showing this output in the CI. My suggestion would be to add the outputs you added to this list: https://github.com/WyriHaximus/github-action-composer-php-versions-in-range/blob/main/.github/workflows/ci.yml#L16-L19

Secondly to show that, add the following at the end of the file:

```yaml
  extensions:
    name: Detected extensions on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    needs:
      - get-supported-php-versions
    runs-on: ${{ matrix.os }}
    steps:
      - run: |
          echo "All require extensions: ${{ needs.get-supported-php-versions.outputs.extensions }}"
          echo "Require extensions: ${{ needs.get-supported-php-versions.outputs.requiredExtensions }}"
          echo "Dev require extensions: ${{ needs.get-supported-php-versions.outputs.requiredDevExtensions }}"
```

2022-08-20 20:32 UTC, WyriHaximus commented on main.js
> +console.log(`All extensions: ${JSON.stringify(allExtensions)}`);
```suggestion
console.log(`All required extensions: ${JSON.stringify(allExtensions)}`);
```

2022-08-22 21:14 UTC, WyriHaximus approved these changes
LGTM, thanks :+1:!

Take your time for the readme updates, I'll merge and tag this as is. And once you have worked out a real-world example, feel free to open a PR for the readme.

2022-08-22 21:15 UTC, WyriHaximus approved these changes

2022-08-22 21:15 UTC, merged

2022-08-22 21:20 UTC, WyriHaximus commented
Just released [`v1.7.0`](https://github.com/WyriHaximus/github-action-composer-php-versions-in-range/releases/tag/v1.7.0] with this.